disable libapreq stuff until it works generically
git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/trunk@1200695 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -163,13 +163,13 @@ fi
 
 apr_src_dir=`cd $apr_src_dir && pwd` 
 
-apreq_configure="srclib/libapreq"
-echo
-echo rebuilding $apreq_configure
-(cd srclib/libapreq && ./buildconf --with-apr="$apr_src_dir") || {
-    echo "./buildconf failed for apreq"
-    exit 1
-}
+#apreq_configure="srclib/libapreq"
+#echo
+#echo rebuilding $apreq_configure
+#(cd srclib/libapreq && ./buildconf --with-apr="$apr_src_dir") || {
+#    echo "./buildconf failed for apreq"
+#    exit 1
+#}
 
 if [ $apr_major_version -lt 2 ] ; then
     if [ "$apu_src_dir" = "srclib/apr-util" ]; then
