APR-util has renamed buildconf.sh to buildconf to match APR and httpd-2.0.
git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/trunk@89864 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -109,8 +109,8 @@ echo rebuilding $apr_configure
 }
 
 echo rebuilding $aprutil_configure
-(cd srclib/apr-util && ./buildconf.sh) || {
-    echo "./buildconf.sh failed for apr-util" 
+(cd srclib/apr-util && ./buildconf) || {
+    echo "./buildconf failed for apr-util" 
     exit 1
 }
 
