give the poor users (i.e. us) a clue that something might be wrong when buildconf fails in subdirectories
git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/trunk@88871 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -103,10 +103,16 @@ config_h_in="include/ap_config_auto.h.in"
 cross_compile_warning="warning: AC_TRY_RUN called without default to allow cross compiling"
 
 echo rebuilding $apr_configure
-(cd srclib/apr && ./buildconf) || exit 1
+(cd srclib/apr && ./buildconf) || {
+    echo "./buildconf failed for apr"
+    exit 1
+}
 
 echo rebuilding $aprutil_configure
-(cd srclib/apr-util && ./buildconf.sh) || exit 1
+(cd srclib/apr-util && ./buildconf.sh) || {
+    echo "./buildconf.sh failed for apr-util" 
+    exit 1
+}
 
 echo rebuilding $pcre_configure
 (cd srclib/pcre && autoconf)
