hook up srclib/libapreq to the build system
git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/trunk@1200590 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/buildconf b/buildconf
--- a/buildconf
+++ b/buildconf
@@ -161,6 +161,14 @@ if [ "$apr_src_dir" = "srclib/apr" ]; then
     rm -f srclib/apr/apr.spec
 fi
 
+apreq_configure="srclib/libapreq"
+echo
+echo rebuilding $apreq_configure
+(cd srclib/libapreq && ./buildconf) || {
+    echo "./buildconf failed for apreq"
+    exit 1
+}
+
 apr_src_dir=`cd $apr_src_dir && pwd` 
 
 if [ $apr_major_version -lt 2 ] ; then
