Cleanup the suEXEC support in APACI and make it more safe:
 1. Add big fat hint in INSTALL about risks and to read the
    htdocs/manual/suexec.html document before using the suexec-related
    configure options.

 2. Make sure the user has at least provided one --suexec-xxxx option
    (specifies suEXEC parameters) in addition to --enable-suexec option.
    If only --enable-suexec is given APACI stops with a hint to INSTALL
    and htdocs/manual/suexec.html documents.

 3. Provide two additional --suexec-xxxx options to make the suEXEC
    configuration complete (especially for package maintainers who else
    had to patch the source tree) by providing ways to configure minimal
    UID/GID and safe PATH, too.


git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@81187 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -164,8 +164,12 @@ layout=0
 
 #   suexec defaults
 suexec=0
+suexec_ok=0
 suexec_caller=www
 suexec_userdir=public_html
+suexec_uidmin=100
+suexec_gidmin=100
+suexec_safepath="/usr/local/bin:/usr/bin:/bin"
 
 #   with support tools
 support=1
@@ -347,6 +351,9 @@ do
             echo " --enable-suexec        enable the suEXEC feature"
             echo " --suexec-caller=NAME   set the suEXEC username of the allowed caller [$suexec_caller]"
             echo " --suexec-userdir=DIR   set the suEXEC user subdirectory [$suexec_userdir]"
+            echo " --suexec-uidmin=UID    set the suEXEC minimal allowed UID [$suexec_uidmin]"
+            echo " --suexec-gidmin=GID    set the suEXEC minimal allowed GID [$suexec_gidmin]"
+            echo " --suexec-safepath=PATH set the suEXEC safe PATH [$suexec_safepath]"
             echo ""
             exit 0
             ;;
@@ -631,9 +638,23 @@ do
             ;;
         --suexec-caller=*)
             suexec_caller="$apc_optarg"
+            suexec_ok=1
             ;;
         --suexec-userdir=*)
             suexec_userdir="$apc_optarg"
+            suexec_ok=1
+            ;;
+        --suexec-uidmin=*)
+            suexec_uidmin="$apc_optarg"
+            suexec_ok=1
+            ;;
+        --suexec-gidmin=*)
+            suexec_gidmin="$apc_optarg"
+            suexec_ok=1
+            ;;
+        --suexec-safepath=*)
+            suexec_safepath="$apc_optarg"
+            suexec_ok=1
             ;;
         * )
             echo "configure:Error: invalid option '$apc_option'" 1>&2
@@ -645,6 +666,20 @@ IFS="$OIFS1"
 if [ ".$apc_prev" != . ]; then
     echo "configure:Error: missing argument to --`echo $apc_prev | sed 's/_/-/g'`" 1>&2
     exit 1
+fi
+
+##
+##  a few errors
+##
+if [ ".$suexec" = .1 ]; then
+    if [ ".$suexec_ok" = .0 ]; then
+        echo "configure:Error: You enabled the suEXEC feature via --enable-suexec but"
+        echo "                 without explicitly configuring it via at least one"
+        echo "                 --suexec-xxxxx option. Seems like you are still not"
+        echo "                 familiar with the suEXEC risks. Please read the INSTALL"
+        echo "                 and htdocs/manual/suexec.html documents first."
+        exit 1
+    fi
 fi
 
 ##
@@ -780,6 +815,9 @@ sed <Makefile.tmpl >$mkf \
 -e "s%@suexec@%$suexec%g" \
 -e "s%@suexec_caller@%$suexec_caller%g" \
 -e "s%@suexec_userdir@%$suexec_userdir%g" \
+-e "s%@suexec_uidmin@%$suexec_uidmin%g" \
+-e "s%@suexec_gidmin@%$suexec_gidmin%g" \
+-e "s%@suexec_safepath@%$suexec_safepath%g" \
 -e "s%@build_support@%$build_support%g" \
 -e "s%@install_support@%$install_support%g" \
 -e "s%@clean_support@%$clean_support%g" \
