Make sure the argument for the --add-module option to APACI's configure script is of type [path/to/]mod_xxx.c because all calculations inside configure and src/Configure depend on this.
PR: 2307


git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@81406 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -423,12 +423,10 @@ do
             ;;
         --add-module=*) 
             file="$apc_optarg"
-            case $file in
-                *.c ) ;;
-                  * ) echo "configure:Error: Module source $file is not a C source file" 1>&2
-                      exit 1 
-                      ;;
-            esac
+            if [ ".`echo $file | egrep '/?mod_[a-zA-Z0-9][a-zA-Z0-9_]*\.c$'`" = . ]; then
+                echo "configure:Error: Module filename doesn't match '/?mod_[a-zA-Z0-9][a-zA-Z0-9_]*\.c'" 1>&2
+                exit 1
+            fi
             if [ ! -f $file ]; then
                 echo "configure:Error: Module source $file not found" 1>&2
                 exit 1
