Let APACI's configure script correctly complain for unknown --enable-XXX and --disable-XXX options.
PR: 3958


git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@82886 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -729,6 +729,10 @@ do
                 suexec ) 
                     suexec=1
                     ;;
+                * ) 
+                    echo "configure:Error: invalid option '$apc_option'" 1>&2
+                    exit 1
+                    ;;
             esac
             ;;
         --disable-*)
@@ -786,6 +790,10 @@ do
                            eval "shared_${apc_optarg}=no" 
                            ;;
                     esac
+                    ;;
+                * ) 
+                    echo "configure:Error: invalid option '$apc_option'" 1>&2
+                    exit 1
                     ;;
             esac
             ;;
