Add a --with-test-suite option for "in-tree" testing
Step one. It's not actually "in-tree" yet, since it requires running
`make install` first, but at least it gives us a `make check`.

git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/trunk-test-integration@1777384 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -295,5 +295,24 @@ update-log-tags update-log-msg-tags:
 	find server modules os -name \*.c|xargs perl \
 		docs/log-message-tags/update-log-msg-tags
 
+# TODO: don't require an install of the server binaries to run the tests
+APXS_LOCATION := $(DESTDIR)$(bindir)/apxs
+
+check:
+	@if test "x$(TEST_SUITE_LOCATION)" = "xno"; then \
+	    echo 'Re-run configure with the --with-test-suite option to enable in-tree tests.'; \
+	    false; \
+	fi
+	@if ! test -f "$(APXS_LOCATION)"; then \
+	    echo "Can't find apxs at '$(APXS_LOCATION)'"; \
+	    echo "Unfortunately the 'in-tree' tests don't run yet without first running 'make install'. Sorry."; \
+	    false; \
+	fi
+	cd "$(TEST_SUITE_LOCATION)" && \
+	    perl Makefile.PL -apxs "$(APXS_LOCATION)" && \
+	    ./t/TEST -clean && \
+	    ./t/TEST -config && \
+	    ./t/TEST
+
 # XXX: This looks awfully platform-specific [read: bad form and style]
 include $(top_srcdir)/os/os2/core.mk
