Make Configure die when a bad switch is given.
Submitted by:	Ben Hyde


git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@80595 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/Configure b/src/Configure
--- a/src/Configure
+++ b/src/Configure
@@ -101,8 +101,9 @@ while [ "x$1" != "x" ]; do
       exit 1
     fi
   else
-    echo "Ignoring command line option '$1'"
-    shift 1
+    echo "ERROR: Bad command line option '$1'"
+    echo "  Please read the file INSTALL."
+    exit 1
   fi
 done
 if [ ! -r $file ]; then
