Oops... we should actually check the return value of the ANSI test :)
git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@78768 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/Configure b/src/Configure
--- a/src/Configure
+++ b/src/Configure
@@ -704,7 +704,16 @@ echo "SHELL=$SHELL">> Makefile.config
 ####################################################################
 # Use TestCompile to see if $(CC) is ANSI
 #
-./helpers/TestCompile ansi
+if ./helpers/TestCompile ansi; then
+    :
+else
+   echo "** A test compilation with your Makefile configuration"
+   echo "** failed. This is mostly like since your C compiler"
+   echo "** is not ANSI. Apache requires an ANSI C Compiler, such"
+   echo "** as gcc."
+   echo " Aborting!"
+   exit 1
+fi
 
 ####################################################################
 # Use TestCompile to look for various LIBS
