Force verbose mode during the sanity check if the check fails
git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@84195 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/Configure b/src/Configure
--- a/src/Configure
+++ b/src/Configure
@@ -2150,13 +2150,23 @@ else
    if ./helpers/TestCompile $vflag sanity; then
       :
    else
-   echo "** A test compilation with your Makefile configuration"
-   echo "** failed.  Re-run your configure script with --verbose"
-   echo "** to get a better idea of what is failing.  Note that"
-   echo "** Apache requires an ANSI C Compiler, such as gcc. "
-   echo " Aborting!"
-   exitcode=1
-   exit 1
+      if [ "x$vflag" = "x-v" ] ; then
+         WHEREERR="above"
+      else
+         WHEREERR="below"
+      fi
+      echo "** A test compilation with your Makefile configuration"
+      echo "** failed.  The $WHEREERR error output from the compilation"
+      echo "** test will give you an idea what is failing. Note that"
+      echo "** Apache requires an ANSI C Compiler, such as gcc. "
+      echo ""
+      echo "======== Error Output for sanity check ========"
+      (./helpers/TestCompile -v sanity)
+      echo "============= End of Error Report ============="
+      echo ""
+      echo " Aborting!"
+      exitcode=1
+      exit 1
    fi
 fi
 
