Backout the EXPAT blarf. Modify the description of EXPAT to explain about the Expat search order, which is new
git-svn-id: https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x@91355 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/Configure b/src/Configure
--- a/src/Configure
+++ b/src/Configure
@@ -1853,27 +1853,33 @@ if [ "x$RULE_WANTHSREGEX" = "xyes" ]; then
 fi
 
 ####################################################################
-## Add in the Expat(-lite) library. Choose whether we want the expat-lite
-## version ('yes'), the system's expat ('no') or for Configure
-## to choose for us ('default' - system is prefered if available).
+## Add in the Expat library if needed/wanted.
 ##
 
-if ./helpers/TestCompile lib expat && [ "x$RULE_EXPAT" != "xyes" ]; then
+# set the default, based on whether expat-lite is bundled. if it is present,
+# then we can always include expat.
+if [ "x$RULE_EXPAT" = "xdefault" ]; then
+    if [ -d ./lib/expat-lite/ ]; then
+        RULE_EXPAT=yes
+    else
+        RULE_EXPAT=no
+    fi
+fi
+
+if [ "x$RULE_EXPAT" = "xyes" ]; then
+    if ./helpers/TestCompile lib expat; then
         echo " + using system Expat"
-	LIBS="$LIBS -lexpat"
-else
-    if [ "x$RULE_EXPAT" = "xno" ]; then
-        echo "ERROR: RULE_EXPAT set to \"no\" but system expat is not available."
-        exit 1
+        LIBS="$LIBS -lexpat"
+    else
+        if [ ! -d ./lib/expat-lite/ ]; then
+            echo "ERROR: RULE_EXPAT set to \"yes\" but is not available."
+	    exit 1
+        fi
+        echo " + using builtin Expat"
+        EXPATLIB="lib/expat-lite/libexpat.a"
+        APLIBDIRS="expat-lite $APLIBDIRS"
+        CFLAGS="$CFLAGS -DUSE_EXPAT -I\$(SRCDIR)/lib/expat-lite"
     fi
-    if [ ! -d ./lib/expat-lite/ ]; then
-        echo "Bundled expat-lite package not available."
-	exit 1
-    fi
-    echo " + using builtin Expat"
-    EXPATLIB="lib/expat-lite/libexpat.a"
-    APLIBDIRS="expat-lite $APLIBDIRS"
-    CFLAGS="$CFLAGS -DUSE_EXPAT -I\$(SRCDIR)/lib/expat-lite"
 fi
 
 ####################################################################
